TS_SEARCH_PATHS=(~/projects ~/code ~/work ~/personal ~/Desktop)
TS_EXTRA_SEARCH_PATHS=(~/.local:1 ~/.config:2)
TS_MAX_DEPTH=2
TS_REPO_CLONE_DIR=~/projects
TS_SESSION_COMMANDS=("nvim" "htop" "lazydocker")
TS_LOG=file | echo
