TS_SEARCH_PATHS=(~/projetos ~/.config/nvim ~/.config/tmux
~/.config/tmux-sessionizer ~/.config/opencode ~/.config/git ~/.config/ghostty
~/.config/leaf)
TS_MAX_DEPTH=2
TS_REPO_CLONE_DIR=~/projetos
TS_SESSION_COMMANDS=("nvim" "htop" "lazydocker" "leaf")
TS_LOG=file | echo
